Some thing about the API used:
    
    I have an API (which I masked),where I need to extract data by Device Category, Device Type, 
    Device ID and Its last communicated time by Customer Name, County and his Location.
    
    As the API been masked, an extract replica of data extracted under the call is pasted below right
    after the API call.

In [1]:
# Importing necessary Libraries

import pandas as pd
import datetime
import requests
import json
from pandas.io.json import json_normalize

In [ ]:
# Making API call with requests Library
##/***Masking the API (with abc.com- Inreal no such API exists)**/##

url = "https://abc.com/research/dashboard/devices"

payload = {"user_name":"john","password":"********"}

response = requests.request("POST", url, data=payload)

# print(response.text)
data = json.loads(response.text)

In [8]:
# Imagine the Response object extracted is as below: (i.e. data object from last line)

data = {
"status": 1,
"data": [
    {
        "country_name": "India",
        "Device_list": [
            {
                "customer_name": "Andrew",
                "location_name": "Chennai",
                "Device_Cat": "Device1",
                "Module_offline_devices": {
                    "DeviceM": [
                        {
                            "Device_id": "A1",
                            "Device_last_comm_time": "2020-01-27 14:11:10"
                        },
                        {
                            "Device_id": "A2",
                            "Device_last_comm_time": "2020-01-27 14:11:10"
                        },
                        {
                            "Device_id": "A3",
                            "Device_last_comm_time": "2020-01-25 14:52:42"
                        }
                    ],
                    "DeviceG": [
                        {
                            "Device_id": "B1",
                            "Device_last_comm_time": "2019-11-27 14:09:00"
                        },
                        {
                            "Device_id": "B2",
                            "Device_last_comm_time": "2019-11-27 14:09:00"
                        }
                    ],
                    "DeviceF": [
                        {
                            "Device_id": "B3",
                            "Device_last_comm_time": "2019-11-27 14:23:00"
                        }
                    ],
                    "gateway": [
                        {
                            "gateway_id": "G1",
                            "Device_last_comm_time": "2018-05-18 12:18:45"
                        },
                        {
                            "gateway_id": "G2",
                            "Device_last_comm_time": ""
                        },
                        {
                            "gateway_id": "G3",
                            "Device_last_comm_time": "2019-12-18 14:15:12"
                        }
                    ]

                }
            },
            {
                "customer_name": "Bob",
                "location_name": "Banglore",
                "Device_Cat": "Device2",
                "Module_offline_devices": {
                    "DeviceM": [
                        {
                            "Device_id": "A10",
                            "Device_last_comm_time": "2019-02-18 16:30:54"
                        },
                        {
                            "Device_id": "A11",
                            "Device_last_comm_time": "2019-02-18 17:41:53"
                        }
                    ],
                    "DeviceG": [],
                    "DeviceF": [
                        {
                            "Device_id": "B10",
                            "Device_last_comm_time": "2019-12-11 12:55:53"
                        }
                    ],
                    "gateway": {
                        "gateway_id": "G10",
                        "Device_last_comm_time": "null"
                    }
                }
            },
            {
                "customer_name": "Michael",
                "location_name": "Hyderabad",
                "Device_Cat": "Device3",
                "Module_offline_devices": {
                    "DeviceM": [
                        {
                            "Device_id": "A20",
                            "Device_last_comm_time": "2019-06-07 15:29:16"
                        },
                        {
                            "Device_id": "A21",
                            "Device_last_comm_time": "2019-02-18 16:30:49"
                        }
                    ],
                    "DeviceG": [],
                    "DeviceF": [
                        {
                            "Device_id": "B20",
                            "Device_last_comm_time": "2019-12-09 14:39:18"
                        }
                    ],
                   "gateway": [
                        {
                            "gateway_id": "G20",
                            "Device_last_comm_time": "2018-05-18 12:18:45"
                        },
                        {
                            "gateway_id": "G21",
                            "Device_last_comm_time": "null"
                        },
                        {
                            "gateway_id": "G22",
                            "Device_last_comm_time": "2019-12-18 14:15:12"
                        }
                    ]
                }
            }
        ]
    }
]
}

In [12]:
# Initialize a empty DataFrame
final_df = pd.DataFrame()

# Looping over to normalize data with json_normalize and append data at each loop to the final_df dataframe

for result in data['data']:
    df_a = json_normalize(data = result['Device_list'], 
                            record_path =['Module_offline_devices','DeviceM'],  
                            meta =['customer_name', 'location_name', 'Device_Cat']) 
    df_a['device_type'] = 'DeviceM'
    df_a['country'] = result['country_name']
    final_df = final_df.append(df_a)

    df_b = json_normalize(data = result['Device_list'], 
                                record_path =['Module_offline_devices','DeviceG'],  
                                meta =['customer_name', 'location_name', 'Device_Cat']) 
    df_b['device_type'] = 'DeviceG'
    df_b['country'] = result['country_name']
    final_df = final_df.append(df_b)

    df_c = json_normalize(data = result['Device_list'], 
                                record_path =['Module_offline_devices','DeviceF'],  
                                meta =['customer_name', 'location_name', 'Device_Cat']) 
    df_c['device_type'] = 'DeviceF'
    df_c['country'] = result['country_name']
    final_df = final_df.append(df_c)

In [11]:
# Examine the final_df dataframe

final_df.head()

,Device_id,Device_last_comm_time,customer_name,location_name,Device_Cat,device_type,country
0,A1,2020-01-27 14:11:10,Andrew,Chennai,Device1,DeviceM,India
1,A2,2020-01-27 14:11:10,Andrew,Chennai,Device1,DeviceM,India
2,A3,2020-01-25 14:52:42,Andrew,Chennai,Device1,DeviceM,India
3,A10,2019-02-18 16:30:54,Bob,Banglore,Device2,DeviceM,India
4,A11,2019-02-18 17:41:53,Bob,Banglore,Device2,DeviceM,India
5,A20,2019-06-07 15:29:16,Michael,Hyderabad,Device3,DeviceM,India
6,A21,2019-02-18 16:30:49,Michael,Hyderabad,Device3,DeviceM,India
0,B1,2019-11-27 14:09:00,Andrew,Chennai,Device1,DeviceG,India
1,B2,2019-11-27 14:09:00,Andrew,Chennai,Device1,DeviceG,India
0,B3,2019-11-27 14:23:00,Andrew,Chennai,Device1,DeviceF,India
1,B10,2019-12-11 12:55:53,Bob,Banglore,Device2,DeviceF,India
2,B20,2019-12-09 14:39:18,Michael,Hyderabad,Device3,DeviceF,India